---
sudo: required
language: python:2.7
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install molecule
  # - pip install required driver (e.g. docker, python-vagrant, shade, boto, apache-libcloud)
  - pip install docker
script:
  - molecule lint
  - molecule test -s docker
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
