---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos7-systemd-docker
    image: centos/systemd
    # image: retr0h/centos7-systemd-ansible:latest
    # image: centos:7
    privileged: true
    command: /usr/sbin/init
    # volumes:
    #   - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: fedora29-docker
    image: geerlingguy/docker-fedora29-ansible
  - name: ubuntu18.04-docker
    image: geerlingguy/docker-ubuntu1804-ansible
  - name: ubuntu16.04-docker
    image: geerlingguy/docker-ubuntu1604-ansible
  - name: debian9-docker
    image: geerlingguy/docker-debian9-ansible
provisioner:
  name: ansible
  options:
    become: true
  lint:
    name: ansible-lint
    options:
      R: true
scenario:
  name: docker
verifier:
  name: testinfra
  directory: ../tests
  options:
    verbose: true
  lint:
    name: flake8
